AddTarget(inpx	app_console
	PROJECT_GROUP Tool
	SOURCE_DIRECTORY
		"${CMAKE_CURRENT_LIST_DIR}"
	INCLUDE_DIRECTORIES
		"${CMAKE_CURRENT_LIST_DIR}/.."
	LINK_TARGETS
		InpxLib
		logging
	LINK_LIBRARIES
		plog
)
