include("${CMAKE_CURRENT_LIST_DIR}/app/flibrary.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/ui/ui.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/logic/logic.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/interface/flint.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/version/version.cmake")
