#pragma once

namespace HomeCompa::Flibrary::ObjectConnectorID
{
constexpr auto BOOKS_SEARCH_FILTER_VALUE_GEOMETRY_CHANGED = "BOOKS_SEARCH_FILTER_VALUE_GEOMETRY_CHANGED";
constexpr auto BOOK_TITLE_TO_SEARCH_VISIBLE_CHANGED = "BOOK_TITLE_TO_SEARCH_VISIBLE_CHANGED";
}
