AddTarget(
	NAME Util
	TYPE shared_lib
	PROJECT_GROUP Util
	SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/util"
	INCLUDE_DIRS
		"${CMAKE_CURRENT_LIST_DIR}"
		"${CMAKE_CURRENT_LIST_DIR}/../ext/plog/include"
	QT_USE
		Core
	LINK_TARGETS
		plog
	MODULES
		qt
	COMPILE_DEFINITIONS
		[ WIN32 PLOG_IMPORT ]
	COMPILER_OPTIONS
		[ MSVC /WX /W4 ]
)
