AddTarget(
	NAME Util
	TYPE shared_lib
	PROJECT_GROUP Util
	SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/util"
	INCLUDE_DIRS
		"${CMAKE_CURRENT_LIST_DIR}"
	QT_USE
		Core
	LINK_TARGETS
	MODULES
		qt
	COMPILER_OPTIONS
		[ MSVC /WX /W4 ]
)
