AddTarget(ver	shared_lib
	PROJECT_GROUP App
	SOURCE_DIRECTORY
		"${CMAKE_CURRENT_LIST_DIR}"
	LINK_LIBRARIES
		Qt${QT_MAJOR_VERSION}::Core
)

add_custom_command(TARGET ver
    POST_BUILD
    COMMAND ${CMAKE_COMMAND} -D FILE=${CMAKE_CURRENT_LIST_DIR}/build.h -P ${CMAKE_CURRENT_LIST_DIR}/inc_build_no.cmake
)
