AddTarget(logging	shared_lib
	SOURCE_DIRECTORY
		${CMAKE_CURRENT_LIST_DIR}
	PROJECT_GROUP Util
	INCLUDE_DIRECTORIES
		"${CMAKE_CURRENT_LIST_DIR}/.."
	LINK_LIBRARIES
		Qt6::Core
		LINK_PUBLIC plog
	COMPILE_DEFINITIONS
		PLOG_EXPORT
)
