AddTarget(
	NAME logging
	TYPE shared_lib
	SOURCE_DIR ${CMAKE_CURRENT_LIST_DIR}
	PROJECT_GROUP Util
	INCLUDE_DIRS
		"${CMAKE_CURRENT_LIST_DIR}/.."
	MODULES
		plog
	COMPILE_DEFINITIONS
		[ WIN32 PLOG_EXPORT ]
	COMPILER_OPTIONS
		[ MSVC /WX /W4 ]
)
